name: azorin_test
description: Презентационный проект отражающий навыки работы и понимание Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  built_value: 8.0.6
  built_collection: 5.0.0
  freezed_annotation: ^0.14.0

  #Forks for migrate_to_null_safety
  built_redux:
    git:
      url: https://github.com/Sunderik/built_redux.git
      ref: master
  flutter_built_redux:
    git:
      url: https://github.com/Sunderik/flutter_built_redux.git
      ref: master

  logger: ^1.0.0

  provider: ^5.0.0

  rxdart: ^0.26.0

  injectable: ^1.4.1 #DI generator
  get_it: ^7.0.0 #DI

  shared_preferences: ^2.0.4 # token, userinfo etc store

  cached_network_image: ^3.0.0 # to show images from the internet and keep them in the cache directory

  redux_persist: ^0.9.0 #no web
  redux_persist_flutter: ^0.9.0 #no web

  http: ^0.13.3 # http requests

  collection: ^1.15.0 # The package contains functions that operate on lists.

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  mockito: ^5.0.9
  build_runner: ^2.1.1
  freezed: ^0.14.0
  pedantic: ^1.9.2
  injectable_generator: ^1.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
